/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
static yyconst short int yy_accept[322] =
    {   0,
        0,    0,   88,   86,   84,   85,   81,   54,   63,   86,
       77,   78,   52,   50,   75,   51,   53,   67,   82,   76,
       61,   56,   62,   79,   80,   55,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   64,   83,   83,
       83,   83,   83,   83,   63,   64,   65,    0,   84,    0,
       70,    0,    0,    0,   71,    0,    0,   74,    0,   67,
       49,   49,   59,   58,   57,   60,   83,   83,   83,   83,
       17,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   65,   83,   83,   83,   83,   83,   83,
       83,   11,   83,   83,   83,   83,   69,   69,   69,   74,

       66,   83,   83,   83,   83,   83,   29,   83,   83,   83,
       83,   83,   83,   42,   83,   83,   83,   83,   83,   83,
       83,   54,   83,   83,   83,   83,   39,   83,   26,   83,
       83,   83,   83,   83,   83,   83,   83,   83,    0,    0,
        0,   83,   83,   83,   16,    6,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   10,   83,   83,   19,   83,   18,   27,   30,
       83,   44,   83,   83,   83,   13,   83,   83,   83,   83,
       83,   68,   68,   68,   83,   83,   83,   83,   28,   83,
       83,   83,   83,   73,   83,   83,   83,   83,   83,   83,

       14,   83,   83,   22,   25,   83,   83,   83,   83,   83,
       83,   83,   15,   83,   83,   47,   41,   83,   83,   46,
       83,   83,   83,   43,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   48,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,    5,   83,   83,   83,
       83,   83,   83,   31,   83,   83,   83,   83,   32,   83,
       83,    9,    3,   83,   24,   83,   83,   83,   83,   45,
       83,   12,    7,   83,   83,   83,   83,   20,   83,   83,
        8,   21,   83,   83,   83,   83,    1,   38,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   72,   83,   33,

       83,    4,   83,   83,   40,   83,   34,   83,   23,   83,
       83,   83,    2,   83,   83,   36,   83,   35,   83,   37,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    5,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   26,   26,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   26,   47,   48,   26,
       22,   23,   24,   25,   26,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   26,   26,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   26,   47,
       48,   26,    1,   49,    1,   50,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    3,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1
    } ;

static yyconst short int yy_base[326] =
    {   0,
        0,    0,  201,   40,   50,   43,   51,   46,   47,   58,
       55,   59,   62,   65,   66,   69,   72,   70,   77,   78,
       81,   85,   93,   82,   96,   97,  101,  104,  105,  108,
      109,  114,  115,  118,  122,  123,  135,  143,  152,  153,
      157,  158,  164,  165,  169,  170,  173,  129,  135,  107,
     1035,  134,    0,  144, 1035,  183,    0,    0,  108,  186,
     1035,  107, 1035, 1035, 1035, 1035,  194,  197,  198,  201,
      202,  205,  206,  214,  210,  209,  213,  220,  224,  241,
      242,  245,  130,  246,  249,  231,  235,  255,  256,  268,
      269,  272,  273,  277,  285,  286,  289,  300,  299,    0,

       87,  296,  306,  307,  314,  318,  319,  325,  328,  331,
      332,  335,  336,  324,  339,  359,  362,  363,  367,  372,
      373,  376,  380,  381,  385,  384,  388,  389,  397,  403,
      406,  414,  415,  418,  403,  421,  425,  429,   84,  181,
      439,  436,  437,  440,  441,  445,  450,  455,  459,  460,
      463,  468,  469,  474,  478,  479,  482,  485,  493,  494,
      500,  504,  508,  518,  521,  522,  527,  530,  531,  535,
      539,  538,  542,  543,  547,  546,  550,  551,  555,  560,
      561,   83,  365,  560,  564,  568,  567,  578,  579,  585,
      590,  593,  596,  597,  601,  604,  605,  608,  612,  619,

      620,  626,  627,  630,  633,  634,  642,  645,  646,  649,
      652,  656,  657,  661,  664,  665,  669,  675,  682,  685,
      686,  689,  693,  696,  699,  700,  703,  707,  708,  711,
      712,  716,  705,  736,  737,  740,  741,  744,  745,  749,
      752,  753,  756,  760,  764,  765,  768,  769,  777,  782,
      785,  786,  789,  792,  798,  793,  799,  802,  803,  806,
      812,  815,  819,  823,  826,  827,  830,  834,  838,  843,
      846,  847,  851,  852,  855,  859,  860,  867,  872,  868,
      875,  878,  879,  882,  885,  886,  889,  893,  897,  898,
      902,  905,  908,  909,  913,  919,  920,  924,  932,  935,

      938,  939,  942,  943,  947,  951,  954,  955,  959,  960,
      964,  965,  969,  972,  976,  979,  980,  985,  986,  989,
     1035, 1025, 1028,   64, 1031
    } ;

static yyconst short int yy_def[326] =
    {   0,
      321,    1,  321,  321,  321,  321,  322,  321,  321,  323,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  321,  321,  321,  321,  322,
      321,  322,  322,  323,  321,  323,  323,  325,  321,  321,
      321,  321,  321,  321,  321,  321,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,   69,  324,  324,   69,   69,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  321,  322,  323,  325,

      321,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,   90,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,   90,  324,  324,  324,  321,  322,
      323,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  321,  322,  323,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,   90,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
        0,  321,  321,  321,  321
    } ;

static yyconst short int yy_nxt[1086] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,    4,   17,   18,   19,   20,   21,   22,
       23,   24,    4,   25,   26,   27,   28,   27,   29,   30,
       31,   32,   27,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   27,   44,   27,   45,   46,   47,
       48,   49,   48,   48,   51,   48,   48,   48,   48,   48,
       48,   52,   48,   52,   55,   48,   67,   48,   56,   48,
       56,   48,   48,   53,   48,   48,   48,   48,   48,   48,
       57,   48,   48,   59,   48,   60,   58,   48,   48,   48,
       48,   48,   48,   62,   48,   48,   61,   48,  182,  182,

       63,   64,  101,   48,   65,   48,   48,   48,   48,   48,
       51,   48,   66,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   97,  101,   48,   48,   48,   48,   48,   53,
       48,   69,   48,   48,   48,   48,   49,   51,   71,   68,
       75,   78,   72,   70,   97,   48,   73,   48,   76,   98,
       55,   74,   80,   48,   79,   48,   53,   82,   77,  122,
       81,   83,   48,   48,   48,   48,   57,   48,   48,   48,
       48,   67,  123,   84,   48,   48,   48,   48,   86,   48,
       48,   48,   48,   48,   51,   48,   85,   90,   91,   55,
       87,   95,   92,   88,   94,   96,  183,   89,   99,   59,

      321,   60,   93,   53,  321,   57,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  103,  321,  102,
      321,  321,  321,  108,  321,  321,  321,  106,  107,  104,
      105,  110,  112,  321,  109,  113,  114,  321,  116,  111,
      115,  321,  321,  321,  321,  321,  321,  321,  321,  321,
       67,  321,  117,  118,   67,  321,  321,  321,  321,  321,
      321,  119,  125,  126,  120,  121,  127,   67,  321,  321,
      321,  321,  321,  321,  321,  321,  129,  321,  321,  321,
      124,  321,  321,  128,  130,  321,  321,  321,  321,  131,

      135,  133,  139,   51,   97,   55,  321,  132,  321,  134,
      321,  321,  141,  140,   99,   98,  321,  321,  321,  321,
      137,   57,   53,  136,  321,  321,  321,  138,  321,  321,
      321,  321,  321,  144,  142,  321,  143,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      154,  321,  145,  321,  321,  155,  146,  148,  321,  147,
      156,  149,  150,  157,  321,  321,  158,  159,   51,  321,
      151,  321,  321,  321,  321,  321,  152,  321,  153,  321,
      183,  321,  321,  321,  321,  321,  321,   53,  321,  160,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  162,  161,  164,  321,  163,  321,
      165,  169,  321,  321,  166,  321,  321,  171,  321,  168,
      321,  321,  170,  167,  321,  321,  321,  321,  321,  177,
      321,  321,  321,  321,   67,  321,  173,  321,  172,  321,
      321,  321,  178,  321,  174,   55,  321,  321,  321,  321,
      321,  321,  321,  321,  184,  321,  176,  321,  181,  175,
      321,   57,  321,  180,  179,  321,  321,  321,  187,  321,
      321,  321,  321,  321,  186,  321,  321,  185,  321,  321,
      321,  321,  321,  321,  321,  189,  321,  188,  321,  321,
      321,  321,  321,  321,  321,  321,  190,  321,  321,  321,

      192,  191,  193,  321,  321,  321,  321,  194,  198,  195,
      321,  321,  321,  197,  321,  200,  321,  321,  321,  201,
      321,  321,  196,  199,  321,  321,  205,  203,  321,  202,
      321,  321,  321,  321,  321,  204,  321,  321,  206,  321,
      321,  321,  321,  321,  321,  321,  207,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  208,  321,   55,  321,  209,  210,
      321,  321,  321,  321,  321,  184,  321,  321,  321,  321,
      321,  321,   57,  211,  213,  214,  212,  218,  321,  321,
      321,  321,  215,  216,  220,  321,  321,  321,  219,  321,

      321,  217,  321,  321,  321,  321,  321,  321,  321,  321,
      221,  321,  222,  321,  321,  321,  321,  321,  321,  321,
      321,  225,  321,  226,  321,  321,  321,  223,  224,  321,
      321,  321,  321,  227,  321,  229,  321,  321,  321,  321,
      321,  228,  321,  321,  321,  321,  321,  321,  321,  230,
      231,  232,  321,  233,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  234,  321,  321,  321,  321,
      235,  321,  238,  321,  321,  321,  321,  321,  321,  321,
      236,  321,  240,  321,  321,  321,  237,  321,  321,  321,
      241,  239,  321,  242,  321,  321,  321,  321,  321,  321,

      321,  321,  243,  321,  244,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  246,  321,  321,  321,
      321,  321,  321,  321,  321,  245,  321,  248,  321,  249,
      247,  257,  321,  321,  250,  252,   67,  254,  321,  321,
      255,  251,  321,  321,  258,  253,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      256,  321,  321,  321,  321,  321,  321,  261,  321,  321,
      321,  260,  321,  259,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  263,  267,  262,  264,  321,  321,  321,
      268,  266,  321,  265,  321,  321,  321,  321,  321,  321,

      269,  321,  321,  321,  321,  321,  270,  271,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  272,
      275,  321,  321,  273,  321,  321,  274,  321,  277,  321,
      278,  321,  276,  321,  279,  321,  321,  321,  321,  321,
      321,  321,  321,  280,  321,  321,  321,  281,  321,  321,
      321,  283,  321,  321,  282,  321,  321,  321,  321,  321,
      285,  321,  321,  321,  321,  321,  321,  321,  284,  321,
      321,  321,  321,  321,  321,  286,  287,  321,  321,  321,
      321,  321,  321,  288,  321,  321,  289,  321,  321,  321,
      321,  321,  321,  290,  321,  321,  321,  321,  321,  321,

      291,  321,  292,  321,  293,  321,  294,  321,  321,  321,
      321,  321,  321,  295,  321,  321,  296,  321,  321,  321,
      321,  321,  321,  321,  298,  321,  321,  297,  301,  321,
      321,  321,  321,  321,  321,  300,  321,  304,  321,  305,
      299,  321,  321,  302,  321,  321,  303,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  307,  321,
      321,  321,  306,  321,  321,  321,  321,  321,  308,  321,
      321,  321,  321,  311,  321,  321,  321,  321,  321,  321,
      309,  321,  321,  310,  321,  321,  321,  312,  321,  321,
      321,  321,  321,  313,  314,  321,  321,  321,  321,  321,

      321,  321,  321,  316,  321,  321,  315,  321,  321,  321,
      321,  321,  321,  321,  318,  317,  319,  321,  321,  321,
      321,  321,  321,  321,  320,   50,  321,   50,   54,  321,
       54,  100,  321,  100,    3,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321
    } ;

static yyconst short int yy_chk[1086] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        4,    5,    4,    6,    7,    6,    8,    9,    8,    9,
        5,    7,    5,    7,   10,   11,  324,   11,   10,   12,
       10,   12,   13,    7,   13,   14,   15,   14,   15,   16,
       10,   16,   17,   18,   17,   18,   17,   19,   20,   19,
       20,   21,   24,   21,   24,   22,   19,   22,  182,  139,

       21,   21,  101,   23,   22,   23,   25,   26,   25,   26,
       50,   27,   23,   27,   28,   29,   28,   29,   30,   31,
       30,   31,   62,   59,   32,   33,   32,   33,   34,   50,
       34,   29,   35,   36,   35,   36,   49,   52,   30,   28,
       32,   33,   30,   29,   48,   37,   31,   37,   32,   52,
       54,   31,   35,   38,   34,   38,   52,   36,   32,   83,
       35,   36,   39,   40,   39,   40,   54,   41,   42,   41,
       42,   83,   83,   37,   43,   44,   43,   44,   39,   45,
       46,   45,   46,   47,  140,   47,   38,   41,   42,   56,
       39,   44,   42,   39,   43,   44,  140,   40,   56,   60,

        3,   60,   42,  140,   67,   56,   67,   68,   69,   68,
       69,   70,   71,   70,   71,   72,   73,   72,   73,   76,
       75,   76,   75,   77,   74,   77,   74,   69,    0,   68,
       78,    0,   78,   71,   79,    0,   79,   70,   70,   69,
       69,   72,   74,    0,   71,   75,   76,    0,   78,   73,
       77,   80,   81,   80,   81,   82,   84,   82,   84,   85,
       86,   85,   78,   79,   87,   88,   89,   88,   89,    0,
        0,   80,   86,   86,   81,   82,   87,   87,   90,   91,
       90,   91,   92,   93,   92,   93,   89,   94,    0,   94,
       85,    0,    0,   88,   90,   95,   96,   95,   96,   90,

       93,   91,   97,   98,   97,   99,  102,   90,  102,   92,
        0,    0,   99,   98,   99,   98,  103,  104,  103,  104,
       95,   99,   98,   94,  105,    0,  105,   96,  106,  107,
      106,  107,    0,  104,  102,  108,  103,  108,  109,    0,
      109,  110,  111,  110,  111,  112,  113,  112,  113,  115,
      114,  115,  105,    0,    0,  114,  106,  109,    0,  108,
      114,  110,  111,  114,    0,    0,  114,  115,  183,  116,
      111,  116,  117,  118,  117,  118,  112,  119,  113,  119,
      183,    0,  120,  121,  120,  121,  122,  183,  122,  116,
      123,  124,  123,  124,  126,  125,  126,  125,  127,  128,

      127,  128,    0,    0,  118,  117,  120,  129,  119,  129,
      121,  125,    0,  130,  122,  130,  131,  128,  131,  124,
        0,    0,  126,  123,  132,  133,  132,  133,  134,  135,
      134,  136,    0,  136,  135,  137,  131,  137,  130,  138,
        0,  138,  135,    0,  132,  141,  142,  143,  142,  143,
      144,  145,  144,  145,  141,  146,  134,  146,  138,  133,
      147,  141,  147,  137,  136,  148,    0,  148,  144,  149,
      150,  149,  150,  151,  143,  151,    0,  142,  152,  153,
      152,  153,    0,    0,  154,  148,  154,  147,  155,  156,
      155,  156,  157,    0,  157,  158,  149,  158,    0,    0,

      151,  150,  152,  159,  160,  159,  160,  153,  157,  154,
      161,    0,  161,  156,  162,  158,  162,    0,  163,  158,
      163,    0,  155,  157,    0,    0,  161,  159,  164,  158,
      164,  165,  166,  165,  166,  160,    0,  167,  162,  167,
      168,  169,  168,  169,    0,  170,  164,  170,  172,  171,
      172,  171,  173,  174,  173,  174,  176,  175,  176,  175,
      177,  178,  177,  178,  165,  179,  184,  179,  167,  171,
      180,  181,  180,  181,  185,  184,  185,  187,  186,  187,
      186,    0,  184,  173,  175,  177,  174,  181,  188,  189,
      188,  189,  178,  179,  186,  190,    0,  190,  185,    0,

      191,  180,  191,  192,    0,  192,  193,  194,  193,  194,
      187,  195,  188,  195,  196,  197,  196,  197,  198,    0,
      198,  192,  199,  193,  199,    0,    0,  190,  191,  200,
      201,  200,  201,  195,    0,  197,  202,  203,  202,  203,
      204,  196,  204,  205,  206,  205,  206,    0,    0,  198,
      199,  200,  207,  202,  207,  208,  209,  208,  209,  210,
        0,  210,  211,    0,  211,  203,  212,  213,  212,  213,
      206,  214,  209,  214,  215,  216,  215,  216,    0,  217,
      207,  217,  211,    0,    0,  218,  208,  218,    0,    0,
      212,  210,  219,  214,  219,  220,  221,  220,  221,  222,

        0,  222,  215,  223,  218,  223,  224,    0,  224,  225,
      226,  225,  226,  227,    0,  227,  221,  228,  229,  228,
      229,  230,  231,  230,  231,  219,  232,  223,  232,  225,
      222,  233,    0,    0,  226,  228,  233,  230,    0,    0,
      231,  227,    0,    0,  233,  229,  234,  235,  234,  235,
      236,  237,  236,  237,  238,  239,  238,  239,    0,  240,
      232,  240,  241,  242,  241,  242,  243,  237,  243,    0,
      244,  235,  244,  234,  245,  246,  245,  246,  247,  248,
      247,  248,    0,  239,  243,  238,  240,  249,    0,  249,
      244,  242,  250,  241,  250,  251,  252,  251,  252,  253,

      245,  253,  254,  256,  254,  256,  246,  248,  255,  257,
      255,  257,  258,  259,  258,  259,  260,    0,  260,  249,
      252,    0,  261,  250,  261,  262,  251,  262,  255,  263,
      256,  263,  253,  264,  257,  264,  265,  266,  265,  266,
      267,    0,  267,  258,  268,    0,  268,  260,  269,    0,
      269,  264,    0,  270,  261,  270,  271,  272,  271,  272,
      267,  273,  274,  273,  274,  275,    0,  275,  266,  276,
      277,  276,  277,    0,    0,  268,  269,  278,  280,  278,
      280,    0,  279,  271,  279,  281,  274,  281,  282,  283,
      282,  283,  284,  275,  284,  285,  286,  285,  286,  287,

      276,  287,  277,  288,  279,  288,  280,  289,  290,  289,
      290,    0,  291,  283,  291,  292,  284,  292,  293,  294,
      293,  294,    0,  295,  286,  295,    0,  285,  291,  296,
      297,  296,  297,    0,  298,  290,  298,  294,    0,  295,
      289,    0,  299,  292,  299,  300,  293,  300,  301,  302,
      301,  302,  303,  304,  303,  304,    0,  305,  297,  305,
        0,  306,  296,  306,  307,  308,  307,  308,  299,  309,
      310,  309,  310,  304,  311,  312,  311,  312,    0,  313,
      301,  313,  314,  303,  314,    0,  315,  306,  315,  316,
      317,  316,  317,  308,  310,  318,  319,  318,  319,  320,

        0,  320,    0,  312,    0,    0,  311,    0,    0,    0,
        0,    0,    0,    0,  315,  314,  317,    0,    0,    0,
        0,    0,    0,    0,  319,  322,    0,  322,  323,    0,
      323,  325,    0,  325,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\analizador_lexico.l"
#define INITIAL 0
#line 2 ".\\analizador_lexico.l"
#include <stdio.h> // Para la función fprintf
#include <stdlib.h> // Para la función exit
FILE *token_file; // Archivo para guardar los tokens
#line 715 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 10 ".\\analizador_lexico.l"


 /* Palabras reservadas */
#line 870 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 322 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1035 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 13 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Algoritmo>\n"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 14 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, FinAlgoritmo>\n"); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 15 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Algoritmo>\n"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 16 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, FinAlgoritmo>\n"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 17 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Definir>\n"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 18 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Como>\n"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 19 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Escribir>\n"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 20 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Escribir>\n"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 21 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Escribir>\n"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 22 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Leer>\n"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 23 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Si>\n"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 24 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Entonces>\n"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 25 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Sino>\n"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 26 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, FinSi>\n"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 27 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Segun>\n"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 28 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Caso>\n"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 29 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, De>\n"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 30 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Otro>\n"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 31 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Modo>\n"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 32 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, FinSegun>\n"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 33 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Mientras>\n"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 34 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Hacer>\n"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 35 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, FinMientras>\n"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 36 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Repetir>\n"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 37 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Hasta>\n"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 38 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Que>\n"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 39 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Para>\n"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 40 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Desde>\n"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 41 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Con>\n"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 42 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Paso>\n"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 43 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, FinPara>\n"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 44 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Funcion>\n"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 45 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, FinFuncion>\n"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 46 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, SubAlgoritmo>\n"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 47 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, FinSubAlgoritmo>\n"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 48 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, SubAlgoritmo>\n"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 49 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, FinSubAlgoritmo>\n"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 50 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Dimension>\n"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 51 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Por>\n"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 52 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Referencia>\n"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 53 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Valor>\n"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 54 ".\\analizador_lexico.l"
{ fprintf(token_file, "<PALABRA_RESERVADA, Fin>\n"); }
	YY_BREAK
/* Tipos de datos */
case 43:
YY_RULE_SETUP
#line 57 ".\\analizador_lexico.l"
{ fprintf(token_file, "<TIPO_DATO, Entero>\n"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 58 ".\\analizador_lexico.l"
{ fprintf(token_file, "<TIPO_DATO, Real>\n"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 59 ".\\analizador_lexico.l"
{ fprintf(token_file, "<TIPO_DATO, Caracter>\n"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 60 ".\\analizador_lexico.l"
{ fprintf(token_file, "<TIPO_DATO, Cadena>\n"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 61 ".\\analizador_lexico.l"
{ fprintf(token_file, "<TIPO_DATO, Texto>\n"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 62 ".\\analizador_lexico.l"
{ fprintf(token_file, "<TIPO_DATO, Logico>\n"); }
	YY_BREAK
/* Operadores de asignación */
case 49:
YY_RULE_SETUP
#line 65 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_ASIGNACION, <->\n"); }
	YY_BREAK
/* Operadores aritméticos */
case 50:
YY_RULE_SETUP
#line 68 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_ARITMETICO, +>\n"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 69 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_ARITMETICO, ->\n"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 70 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_ARITMETICO, *>\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 71 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_ARITMETICO, />\n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 72 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_ARITMETICO, %>\n"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 73 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_ARITMETICO, ^>\n"); }
	YY_BREAK
/* Operadores relacionales */
case 56:
YY_RULE_SETUP
#line 76 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_RELACIONAL, =>\n"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 77 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_RELACIONAL, ==>\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 78 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_RELACIONAL, <>>\n"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 79 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_RELACIONAL, <=>\n"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 80 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_RELACIONAL, >=>\n"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 81 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_RELACIONAL, <>\n"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 82 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_RELACIONAL, >>\n"); }
	YY_BREAK
/* Operadores lógicos */
case 63:
YY_RULE_SETUP
#line 85 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_LOGICO, Y>\n"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 86 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_LOGICO, O>\n"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 87 ".\\analizador_lexico.l"
{ fprintf(token_file, "<OPERADOR_LOGICO, NO>\n"); }
	YY_BREAK
/* Constantes numéricas sin signo */
case 66:
YY_RULE_SETUP
#line 90 ".\\analizador_lexico.l"
{ fprintf(token_file, "<CONST_REAL, %s>\n", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 91 ".\\analizador_lexico.l"
{ fprintf(token_file, "<CONST_ENTERO, %s>\n", yytext); }
	YY_BREAK
/* Constantes numéricas con signo */
case 68:
YY_RULE_SETUP
#line 94 ".\\analizador_lexico.l"
{ fprintf(token_file, "<CONST_REAL, %s>\n", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 95 ".\\analizador_lexico.l"
{ fprintf(token_file, "<CONST_ENTERO, %s>\n", yytext); }
	YY_BREAK
/* Constantes de texto con comillas dobles */
case 70:
YY_RULE_SETUP
#line 98 ".\\analizador_lexico.l"
{ fprintf(token_file, "<CONST_TEXTO, %s>\n", yytext); }
	YY_BREAK
/* Constantes de texto con comillas simples */
case 71:
YY_RULE_SETUP
#line 101 ".\\analizador_lexico.l"
{ fprintf(token_file, "<CONST_TEXTO, %s>\n", yytext); }
	YY_BREAK
/* Constantes lógicas */
case 72:
YY_RULE_SETUP
#line 104 ".\\analizador_lexico.l"
{ fprintf(token_file, "<CONST_LOGICO, Verdadero>\n"); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 105 ".\\analizador_lexico.l"
{ fprintf(token_file, "<CONST_LOGICO, Falso>\n"); }
	YY_BREAK
/* Ignorar Comentarios */
case 74:
YY_RULE_SETUP
#line 108 ".\\analizador_lexico.l"
;
	YY_BREAK
/* Delimitadores */
case 75:
YY_RULE_SETUP
#line 111 ".\\analizador_lexico.l"
{ fprintf(token_file, "<DELIMITADOR, ,>\n"); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 112 ".\\analizador_lexico.l"
{ fprintf(token_file, "<DELIMITADOR, ;>\n"); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 113 ".\\analizador_lexico.l"
{ fprintf(token_file, "<DELIMITADOR, (>\n"); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 114 ".\\analizador_lexico.l"
{ fprintf(token_file, "<DELIMITADOR, )>\n"); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 115 ".\\analizador_lexico.l"
{ fprintf(token_file, "<DELIMITADOR, [>\n"); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 116 ".\\analizador_lexico.l"
{ fprintf(token_file, "<DELIMITADOR, ]>\n"); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 117 ".\\analizador_lexico.l"
{ fprintf(token_file, "<DELIMITADOR, \">\n"); }
	YY_BREAK
/* Simbolos extras */
case 82:
YY_RULE_SETUP
#line 120 ".\\analizador_lexico.l"
{ fprintf(token_file, "<SIMBOLO, :>\n"); }
	YY_BREAK
/* Identificadores */
case 83:
YY_RULE_SETUP
#line 123 ".\\analizador_lexico.l"
{ fprintf(token_file, "<IDENTIFICADOR, %s>\n", yytext); }
	YY_BREAK
/* Ignora espacios en blanco y tabulaciones */
case 84:
YY_RULE_SETUP
#line 126 ".\\analizador_lexico.l"
;
	YY_BREAK
/* Reconocer saltos de línea */
case 85:
YY_RULE_SETUP
#line 129 ".\\analizador_lexico.l"
{ fprintf(token_file, "<SALTO_LINEA>\n"); }
	YY_BREAK
/* Caracteres no reconocidos */
case 86:
YY_RULE_SETUP
#line 132 ".\\analizador_lexico.l"
{ fprintf(token_file, "<CARACTER_NO_RECONOCIDO, %s>\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 134 ".\\analizador_lexico.l"
ECHO;
	YY_BREAK
#line 1405 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 322 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 322 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 321);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 134 ".\\analizador_lexico.l"


int main(int argc, char **argv) {
    if (argc > 1)
        yyin = fopen(argv[1], "r");
    else
        yyin = stdin;

    token_file = fopen("tokens.txt", "w");
    yylex();
    fclose(token_file);
    return 0;
}